nodeLinker: node-modules

npmScopes:
  packlink:
    npmAlwaysAuth: true
    npmAuthToken: "${PACKLINK_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
  shipengine:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://registry.npmjs.org"
